---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: 在部署 Astra Trident 之前，您必须在主机上安装和配置必要的协议前提条件。 
---
= 部署的前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署 Astra Trident 之前，您必须在主机上安装和配置必要的协议前提条件。



== 验证要求

* 验证您的部署是否满足所有要求 link:../trident-get-started/requirements.html["要求"]。
* 验证您是否安装了受支持的 Docker 版本。如果您的 Docker 版本已过时， https://docs.docker.com/engine/install/["安装或更新它"^]。
+
[listing]
----
docker --version
----
* 验证是否已在主机上安装和配置协议前提条件：


[cols="3*"]
|===
| 协议 | 操作系统 | 命令 


| NFS  a| 
RHEL 8+
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`



| iSCSI  a| 
RHEL 8+
 a| 
. 安装以下系统软件包：
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. 检查 iscsi-initiator-utils 版本是否为 6.2.0.877-2.el7 或更高版本：
+
`rpm -q iscsi-initiator-utils`

. 将扫描设置为手动：
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. 启用多路径：
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`

+

NOTE: 确保 `etc/multipath.conf` 包含 `find_multipaths no` 下 `defaults`。

. 请确保 `iscsid` 和 `multipathd` 正在运行：
+
`sudo systemctl enable --now iscsid multipathd`

. 启用并启动 `iscsi`：
+
`sudo systemctl enable --now iscsi`





| iSCSI  a| 
Ubuntu
 a| 
. 安装以下系统软件包：
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. 检查 open-iscsi 版本是否为 2.0.877-5ubuntu2.10 或更高版本（对于双子系统）或 2.0.877-7.1ubuntu6.1 或更高版本（对于 Focal ）：
+
`dpkg -l open-iscsi`

. 将扫描设置为手动：
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. 启用多路径：
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`

+

NOTE: 确保 `etc/multipath.conf` 包含 `find_multipaths no` 下 `defaults`。

. 请确保 `open-iscsi` 和 `multipath-tools` 已启用且正在运行：
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`



|===